### ISSUE TITLE
why running the same sql cost 2 times time

### ISSUE THREAD

**Issue by l1t1** [datafuselabs/datafuse#816] opened 2021-06-11 03:05 UTC
Make sure to check documentation https://datafuse.rs first. 
```
-gtj:~/fuse$ chmod +x fusequery-v0.4.19*
[1]+  已终止               nohup ./fusequery-v0.4.18-nightly-linux-aarch64
kylin@kylin-gtj:~/fuse$ nohup ./fusequery-v0.4.19-nightly-linux-aarch64 &
[1] 3569
kylin@kylin-gtj:~/fuse$ nohup: 忽略输入并把输出追加到'nohup.out'

kylin@kylin-gtj:~/fuse$ mysql -h127.0.0.1 -P3307
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 5.1.10-alpha-msql-proxy

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select version();
+---------------------------------------------------------------------------------------------+
| version(FuseQuery v-0.1.0-c8be40e-simd(1.54.0-nightly-2021-06-10T16:22:03.497194058+00:00)) |
+---------------------------------------------------------------------------------------------+
| FuseQuery v-0.1.0-c8be40e-simd(1.54.0-nightly-2021-06-10T16:22:03.497194058+00:00)          |
+---------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT avg(number) a FROM (select * from numbers_mt ( 10000000000)) order by a;
+--------------------+
| a                  |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (7.70 sec)

mysql> SELECT avg(number) a FROM (select * from numbers_mt ( 10000000000)) ;
+--------------------+
| a                  |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (4.84 sec)

mysql> SELECT avg(number) a FROM (select * from numbers_mt ( 10000000000)) ;
+--------------------+
| a                  |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (8.57 sec)
```

**Comment by wangzhen11aaa** [comment] 2021-06-11 03:38
![image](https://user-images.githubusercontent.com/7311971/121627135-62c08500-caa9-11eb-8653-504b27d44587.png)
I test same sql via datafuse and ck on my local environment.

**Comment by wangzhen11aaa** [comment] 2021-06-11 03:43
I personally think the pipeline for this sql is simple, (maybe not), but it should not behave like that. Thanks advance.

**Comment by sundy-li** [comment] 2021-06-11 03:43
@wangzhen11aaa  Thanks for the report. 

You can try `SELECT avg(number) a FROM numbers_mt ( 10000000000);` instead, and I will investigate your SQL, maybe it's the problem of pipeline.

**Comment by sundy-li** [comment] 2021-06-11 03:54
make profile can't reproduce in master code.
```

mysql> select avg(number)  from numbers_mt ( 10000000000);
+--------------------+
| avg(number)        |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (0.61 sec)

mysql> SELECT avg(number) a FROM (select * from numbers_mt ( 10000000000)) ;
+--------------------+
| a                  |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (0.69 sec)

```

**Comment by sundy-li** [comment] 2021-06-11 03:58
> 2 times time

This may be the cause of context runtime, cc @zhang2014

**Comment by l1t1** [comment] 2021-06-11 04:14
I run it many times. the difference does exist. 
```
mysql> 
mysql> SELECT avg(number) a FROM numbers_mt ( 10000000000);
+--------------------+
| a                  |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (6.81 sec)

mysql> SELECT avg(number) a FROM (select * from numbers_mt ( 10000000000)) ;
+--------------------+
| a                  |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (5.44 sec)

mysql> SELECT avg(number) a FROM (select * from numbers_mt ( 10000000000)) ;
+--------------------+
| a                  |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (8.06 sec)

mysql> SELECT avg(number) a FROM numbers_mt ( 10000000000);
+--------------------+
| a                  |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (6.84 sec)

mysql> SELECT avg(number) a FROM (select * from numbers_mt ( 10000000000)) ;
+--------------------+
| a                  |
+--------------------+
| 1310651184.7580898 |
+--------------------+
1 row in set (7.57 sec)

```

**Comment by l1t1** [comment] 2021-06-11 04:18
[nohup.out.zip](https://github.com/datafuselabs/datafuse/files/6635793/nohup.out.zip)

**Comment by sundy-li** [comment] 2021-06-11 05:43
@wangzhen11aaa  It's related to log level, which is fixed in #801, you could try 

`./fuse-query --log-level warn`

**Comment by wangzhen11aaa** [comment] 2021-06-11 06:00
> @wangzhen11aaa It's related to log level, which is fixed in #801, you could try
> 
> `./fuse-query --log-level warn`

ok.

**Comment by wangzhen11aaa** [comment] 2021-06-11 06:13
datafuse :) SELECT avg(number) a FROM (select * from numbers_mt ( 1000000000)) ;

SELECT avg(number) AS a
FROM
(
    SELECT *
    FROM numbers_mt(1000000000)
)

Query id: b7bd7486-cb35-4b48-a6a1-be01fa59bf4a

↑ Progress: 2.69 million rows, 21.54 MB (609.42 million rows/s.↗ Progress: 122.47 million rows, 980.64 MB (3.46 billion rows/s→ Progress: 247.21 million rows, 1.98 GB (3.72 billion rows/s.,↘ Progress: 364.57 million rows, 2.92 GB (3.71 billion rows/s.,↓ Progress: 488.64 million rows, 3.91 GB (3.72 billion rows/s.,↙ Progress: 608.47 million rows, 4.87 GB (3.69 billion rows/s.,← Progress: 655.11 million rows, 5.25 GB (3.61 billion rows/s.,↖ Progress: 751.63 million rows, 6.02 GB (3.55 billion rows/s.,↑ Progress: 862.79 million rows, 6.91 GB (3.57 billion rows/s.,↗ Progress: 978.54 million rows, 7.84 GB (3.58 billion rows/s.,
┌───────────a─┐
│ 499999999.5 │
└─────────────┘
→ Progress: 978.54 million rows, 7.84 GB (3.46 billion rows/s.,↘ Progress: 1.00 billion rows, 8.01 GB (3.31 billion rows/s., 2

1 rows in set. Elapsed: 0.302 sec. Processed 1.00 billion rows, 8.01 GB (3.31 billion rows/s., 26.48 GB/s.)
Fast now.

**Comment by BohuTANG** [comment] 2021-06-11 06:16
I will finished https://github.com/datafuselabs/datafuse/issues/794 ASAP, it's helpful to determine this case.

**Closed** 2021-06-15 14:23 UTC
Labels: question
